### ISSUE TITLE
Public Ansible Project Meeting Agenda - January 2018

### ISSUE THREAD

**Issue by thaumos** [ansible/community#291] opened 2017-12-19 20:02 UTC
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by thaumos** [comment] 2018-01-02 19:11
2018 - 01 - 02 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-02/ansible_core.2018-01-02-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-02/ansible_core.2018-01-02-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-02/ansible_core.2018-01-02-19.00.log.html

**Comment by itdependsnetworks** [comment] 2018-01-03 13:52
Want to start back the conversations on gather_facts, current issue opened: https://github.com/ansible/ansible/issues/34109

Some backstory: 

Original 
https://github.com/ansible/ansible/pull/20717

Meeting where it was previously decided not to change.
https://meetbot.fedoraproject.org/ansible-meeting/2017-07-13/core_meeting.2017-07-13-15.00.log.html

Relevant IRC logs:

```
[2017-04-20T12:45:26-0400] <sivel> I think regardless of 20717, there will still be a long tail on `setup`, since many people call setup directly
[2017-04-20T12:45:33-0400] <sivel> it may fix some problems immediately, but not all
[2017-04-20T12:45:58-0400] <@bcoca> sivel: _setup will be found for those using the action in module, but won't trip setuptools
[2017-04-20T12:46:08-0400] <@bcoca> ^ aliases!
[2017-04-20T12:46:13-0400] <@bcoca> first thing i implemented when hired
[2017-04-20T12:46:27-0400] <sivel> yeah, I was saying, if you still had a `setup.py`, people calling `setup` directly could still have problems
[2017-04-20T12:46:53-0400] <@bcoca> yes as it would still override
[2017-04-20T12:47:25-0400] <@bcoca> hence the 'long tail' of really getting rid of setup as we would have to push people to stop using it
[2017-04-20T12:48:10-0400] <@bcoca> itdependsnetwork: and at most it will be 2.4, we dont add features like that in minor versions
[2017-04-20T12:48:12-0400] <itdependsnetwork> ok, so that is why it is so long. It's not just "gather_facts: yes"
[2017-04-20T12:48:20-0400] <@abadger1999> bcoca: It will trip setuptools I think.  But the effect will be minimized
[2017-04-20T12:48:25-0400] <@bcoca> itdependsnetwork: if it were just that .. trivial
[2017-04-20T12:48:38-0400] <itdependsnetwork> ok, did not understand that
[2017-04-20T12:48:40-0400] <@bcoca> abadger1999: yes, that is the purpose of the PR, it will only trip for people explicitly using setup
[2017-04-20T12:48:42-0400] <@abadger1999> I think _setup.py and setup.py will still conflict in PluginLoader
[2017-04-20T12:48:58-0400] <@abadger1999> btut since ansible internally is calling gather_facts, it won't run into it internally
[2017-04-20T12:49:02-0400] <@abadger1999> <nod>
[2017-04-20T12:49:03-0400] <@abadger1999> yep.
[2017-04-20T12:49:05-0400] <@bcoca> my Pr makes setup an alias to allow for explicit calls, but removes it from implicit
[2017-04-20T12:49:05-0400] <@abadger1999> agreed
[2017-04-20T12:49:48-0400] <@bcoca> so it shoudl solve the problem for those in conflict with minor adjustment to playbooks that call setup explicitly
[2017-04-20T12:49:57-0400] <itdependsnetwork> If I am only worried about people doing a "gather_facts: yes" does 20717 fix?
[2017-04-20T12:50:00-0400] <@bcoca> for rest ... we need deprecation notice
[2017-04-20T12:50:08-0400] <@bcoca> itdependsnetwork: yes
[2017-04-20T12:50:13-0400] <itdependsnetwork> +1
[2017-04-20T12:50:23-0400] <itdependsnetwork> that is all I am worried about
[2017-04-20T12:50:40-0400] <@bcoca> sadly, we have to worry about more cases
[2017-04-20T12:50:42-0400] <@bcoca> but its a start
[2017-04-20T12:50:46-0400] <itdependsnetwork> I know :)
[2017-04-20T12:51:16-0400] <itdependsnetwork> and it is still considered too large to be considered for 2.3.X?
```

As per 6 month old subject to change info from: @thaumos should be looking to change in 2.5 
```
[2017-07-13T12:16:54-0400] <itdependsnetwork> just realized meeting is going on, did I miss facts vs setup talk?
[2017-07-13T12:17:02-0400] <thaumos> yep, issue was closed.
[2017-07-13T12:17:12-0400] <itdependsnetwork> meaning resolved?
[2017-07-13T12:17:20-0400] <thaumos> meaning we aren't merging in the change.
[2017-07-13T12:17:25-0400] <itdependsnetwork> why?
[2017-07-13T12:17:39-0400] <thaumos> because the plan is to change the way facts work in the near future.
[2017-07-13T12:17:54-0400] <thaumos> so it seemed silly to bikeshed around a name to have for something that won't exist in the future.
[2017-07-13T12:18:01-0400] <itdependsnetwork> in the meantime I am dealing with user issues that no one want to fix
[2017-07-13T12:18:12-0400] <itdependsnetwork> not so silly to me
[2017-07-13T12:18:43-0400] <thaumos> the intent is to change to the new framework within a release or two.
[2017-07-13T12:19:04-0400] <itdependsnetwork> I get it, I won't win
[2017-07-13T12:19:18-0400] <itdependsnetwork> just real frustrating on what will or won't get fixed
[2017-07-13T12:20:20-0400] <thaumos> It will get fixed by changing the framework.  The concept of "setup" as a module keyword won't exist in the next release.
[2017-07-13T12:21:28-0400] <itdependsnetwork> so there will or will not be a setup.py file in ansible module path in 2.4?
[2017-07-13T12:21:38-0400] <thaumos> in 2.4, there will be.
[2017-07-13T12:22:01-0400] <thaumos> in 2.5 there will most likely not
```

**Comment by jvanderhoof** [comment] 2018-01-03 22:23
I'd like to talk through next steps for PR: https://github.com/ansible/ansible/pull/34280

**Comment by abadger** [comment] 2018-01-03 23:31
Would like a discussion and vote to deprecate and remove DEFAULT_MODULE_LANG and DEFAULT_MODULE_SET_LOCALE.  MODULE_LANG was implemented to allow modules to screenscrape from CLI utilities that they invoked.  However, that never worked well because our defaults used the local machine's locale which made the remote messages vary from user to user.  We then created helper functions so that modules could set those environment variables prior to invoking any commands via AnsibleModule.run_command() and ported modules to use that.  This was so successful that when people complained that we were setting LC_ALL, we were able to create MODULE_SET_LOCALE to let them completely disable the use of MODULE_LANG and modules continued to work.  In 2.2 we changed the default of MODULE_SET_LOCALE to False and no one seems to have noticed.  I think it's time that we deprecate these settings and get rid of them in 4 releases.

**Comment by pilou-** [comment] 2018-01-04 08:41
I would like to discuss:
- https://github.com/ansible/ansible/pull/25519 (`filesystem` module)
- https://github.com/ansible/ansible/pull/33967 (add and use `check_file_absent_if_check_mode` method in `lib/ansible/module_utils/basic.py`)

**Comment by maxamillion** [comment] 2018-01-04 22:45
https://github.com/ansible/ansible/issues/33177

In Ansible 2.3, it appears that the function `_get_hostgroup_vars` from the `Inventory` class handled the scenario of a playbook that included another playbook and kept the path of the original playbook in scope. However, in 2.4 with the transition to inventory plugins, the basedirs for the playbook are determined by the DataLoader which doesn't appear to have any knowledge of the original playbook that did the include/import. I would like to discuss a preferred method to handle playbook adjacent `group_vars` directories in Ansible >2.4.

(Thanks to bcoca, jimi-c, and sivel for helping me get to the root cause of this)

**Comment by sivel** [comment] 2018-01-04 23:03
https://github.com/ansible/ansible/pull/34427

`LooseVersion` comparison in py3 is subject to exceptions due to comparing int and str.  That PR implements a potential fix, but it applies elsewhere too, not just to galaxy role version comparison.

Do we go with that PR, move the new class to a different location for use elsewhere (module_utils)?  Or do we want to think about using pypa/packaging instead.  `SafeLooseVersion` would be easier to ship in module_utils for modules that can utilize it.

**Comment by gundalow** [comment] 2018-01-08 12:52
**Deprecation **

While working on https://github.com/ansible/ansible/pull/34100 it seems there is some confusion around what `version` means in terms of deprecation

Currently we have a few ways of notifying of deprecation in Ansible:

* Module deprecation (git mv $foo.py _$foo.py & `deprecation:` in `DOCUMENTATION` block)
* `display.deprecated('Use foo instead', version='2.4')`
    * `version` here is used inconsistently to mean start or end of cycle.
* `module.deprecate(("State 'removed' is deprecated. Using state 'absent' instead.", version="2.9")`
* Deprecation in config
* anywhere else?

Since the original code was added for the above we have versioned documentation. Which makes some of the easier.

There is confusion if `version` means "start of deprecation cycle" or "end of deprecation cycle"


**Questions/ideas**

1. Should the above all mean the same
   1. `will_be_deleted_in_version`
      * = (version of devel + 4)
      * If we ignore that there may not be a 2.9, and we jump straight to 3.0, is this OK?
   1. `deprecated_as_of_version`
      * When the code was updated = deprecated as of version
      * We now have versioned documentation
      * Are there ever any cases of wanting to give notice that something will be deleted, but we don't know exactly which release?

1. Should we rename the variable to be clearer
1. Better docs
   1. Deprecated modules to link to the porting page
   1.  Porting page to link to Maintenance and releases page
1. When `devel` version++ how can we detect the three cases and `git rm` as needed?



Porting page: http://docs.ansible.com/ansible/devel/porting_guides.html

Maintenance and releases page: https://docs.ansible.com/ansible/devel/release_and_maintenance.html

**Comment by andreaso** [comment] 2018-01-08 13:02
Would like to bring up the _cloudflare_dns_ bugfix https://github.com/ansible/ansible/pull/31800, and woulat it would take to get it merged.

**Comment by gundalow** [comment] 2018-01-08 14:24
The 2.5 freeze dates (merge deadlines) have been pushed out by a week.

Please see updated dates 
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst

To see whats change please see https://github.com/ansible/ansible/commit/1826c27e6841eb313dc3a05dc7f19c96e42c7fbf

**Comment by thaumos** [comment] 2018-01-09 20:01
2018 - 01 -09 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-09/ansible_core.2018-01-09-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-09/ansible_core.2018-01-09-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-09/ansible_core.2018-01-09-19.00.log.html

**Comment by tdtrask** [comment] 2018-01-11 04:29
I would like to discuss [https://github.com/ansible/ansible/issues/34325](https://github.com/ansible/ansible/issues/34325) and the fix at [https://github.com/ansible/ansible/issues/34325](https://github.com/ansible/ansible/pull/34419). The fix ensures that any packages set to 'present' are installed as top-level packages, not just as dependencies for other packages. The new concern raised by @abadger is for state 'absent'. For the Alpine Linux apk package manager, it is not possible to uninstall a package that is installed as a dependency. In fact, the add and del subcommands do not directly install or remove packages. What they do is add rules to the /etc/apk/world file, which are then implemented by the package manager based upon dependencies. The question is whether 'absent' should fail if the package is still installed as a dependency of another package.

**Comment by gundalow** [comment] 2018-01-11 11:10
Proposal: Standard way to influence return values
From @dagwieers https://github.com/ansible/proposals/issues/93

**Comment by dagwieers** [comment] 2018-01-11 15:11
Another one: https://github.com/ansible/ansible/pull/26889

**Comment by thaumos** [comment] 2018-01-11 16:38
2018 - 01 - 11 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-11/ansible_core.2018-01-11-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-11/ansible_core.2018-01-11-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-11/ansible_core.2018-01-11-15.00.log.html

**Comment by abadger** [comment] 2018-01-16 20:56
2018 - 01 - 16 Meeting

* Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-16/ansible_core.2018-01-16-19.06.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-16/ansible_core.2018-01-16-19.06.txt
* Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-16/ansible_core.2018-01-16-19.06.log.html

**Comment by sivel** [comment] 2018-01-18 15:48
Inventory paths with commas: https://github.com/ansible/ansible/pull/35002

**Comment by Akasurde** [comment] 2018-01-18 15:54
I would like to discuss an idea about new label to identify work progress of issue. This label can be applied to issue which has an open PR. Something `has_pr` or `working`.

This will identify if there is a PR or not without even opening this issue's details page.

**Comment by gundalow** [comment] 2018-01-18 16:02
2018-01-18 Meeting:

* Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-18/ansible_core.2018-01-18-15.01.html
* Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-18/ansible_core.2018-01-18-15.01.txt
* Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-18/ansible_core.2018-01-18-15.01.log.html

**Comment by gundalow** [comment] 2018-01-18 16:03
Autogenerated modules

https://github.com/ansible/ansible/pull/35014 (gundalow, 15:06:51)

* #35014 has till the "community" freeze as a) None of GCP is support: core b) module_util changes are only to new in 2.5 modules, therefore no risk of breaking anything else (gundalow, 15:47:10)

* OPTION 1) We have the bot and ANSIBLE_METADATA dictate auto closing issues or PRs for these modules. (requires a proposal)
* OPTION 2) 100% ignoring that they are auto generated (no exceptions), no pointing people elsewhere, just forgetting where they came from, treated like any other module
Remember to consider how this applies to existing auto generated modules, such as `network/avi`

**Comment by thaumos** [comment] 2018-01-23 20:01
2018 - 01 - 23 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-23/ansible_core.2018-01-23-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-23/ansible_core.2018-01-23-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-23/ansible_core.2018-01-23-19.00.log.html

**Comment by maxamillion** [comment] 2018-01-24 21:12
An user suggests that the `service` module should not error when taking action on services that are not installed on the remote host, but I disagree. However, I would be interested in the consensus from the community on this topic.

https://github.com/ansible/ansible/issues/35293

**Comment by thaumos** [comment] 2018-01-24 22:24
Vote on changing time from 1500 UTC.  Suggesting 1600 or 1700 UTC.

**Comment by maxamillion** [comment] 2018-01-24 23:25
+1 to either 1600 or 1700 UTC

**Comment by eikef** [comment] 2018-01-25 15:07
I'd like to request a further review of ansible/ansible#33419 and merge if possible.

**Comment by thaumos** [comment] 2018-01-25 15:18
2018 - 01 - 25 Meeting:

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-25/ansible_core.2018-01-25-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-01-25/ansible_core.2018-01-25-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-01-25/ansible_core.2018-01-25-15.00.log.html

**Comment by Akasurde** [comment] 2018-01-29 08:14
I would like to discuss this issue - related to Python 3.6 and LooseVersion. Following issues are occurred due to this -

- https://github.com/ansible/ansible/issues/35435
- https://github.com/ansible/ansible/issues/35417
- https://github.com/ansible/ansible/issues/32301

Basic cause of this is [Python Bug](https://bugs.python.org/issue14894)

**Comment by evrardjp** [comment] 2018-01-29 16:54
I'd like to discuss the inclusion of config_template as a community action plugin.
https://github.com/ansible/ansible/pull/35453 .

**Comment by sivel** [comment] 2018-01-30 18:01
Should we support old TLS/SSL versions: https://github.com/ansible/ansible/pull/35462

**Closed** 2018-02-06 20:21 UTC
Labels: core, meeting_agenda
