### ISSUE TITLE
OpenStack community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#447] opened 2019-02-20 23:51 UTC
[![Github openstack issues](https://img.shields.io/github/issues/ansible/ansible/openstack.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:openstack) [![Github openstack PRs](https://img.shields.io/github/issues-pr/ansible/ansible/openstack.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:openstack) [![openstack pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/447.svg?label=pinboard+update)](https://github.com/ansible/community/issues/447)

We could collectively benefit from forming a Working Group related to OpenStack integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this *issue* is a call for potential interested parties (earlier and existing contributors to Ansible).  The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing OpenStack PRs
- work collectively on the OpenStack roadmap
- provide a single-point-of-contact for interested OpenStack contributors
- collaborate on [an OpenStack-specific Wiki](https://github.com/ansible/community/wiki/OpenStack)
- have a $team_openstack in BOTMETA.yml for auto-notifying team members
- implement auto-labeling OpenStack issues and PRs

**Comment by dagwieers** [comment] 2019-02-21 00:31
cc @mavimo @jochu @bennojoy @lorin @goozbach @djoreilly @mscherer @CharlesBlonde @berendt @retr0h @sheldonh @bcrochet @tidzo @joshuaconner @risaacson @kvdveer @dmage @vadimkuznetsov @CaptTofu @darKoram @ephur @tongpu @carsongee @hacosta @ryanpetrello @emonty @msabramo @RaymiiOrg @tnoff @jorisroovers @ericwb @mcameron @stygstra @paolo-de-rosa @tkinz27 @t0mk @romain-dartigues @cchurch @larsks @teolupus @yfried @jhesketh @Shrews @cboylan @gl0bus @donovan @annegentle @qnick @TerryHowe @cantorek

**Comment by dagwieers** [comment] 2019-02-21 00:50
cc @bbyhuy @alvaroaleman @bencord0 @dmsimard @inc0 @mgale @ruizink @manics @kuboj @precurse @Thingee @thotypous @mnaser @albertomurillo @cmurphy @logan2211 @samvarankashyap @camradal @morphje  @dbckz @pwnall @tatsuyafw @mkczuk @pshen @phongle1205 @petershrom @rcarrillocruz @rollcat @userlerueda @precurse @nhicher @ioggstream @JonTheNiceGuy @gandelman-a @Elachance @jamielennox @fridim @atosatto @TalShafir @albertomurillo @kgottholm @san7ket @pshen @kuboj @bluesalt @mkosobucki @Miouge1 @nhicher @Durburz @rumenvasilev @jrandall @G5imm9ow @BhujayKumarBhatta @Crapworks @ssbarnea

**Comment by dagwieers** [comment] 2019-02-21 00:59
cc @nanjj @markgoddard @snecklifter @rsevilla87 @kandsten @dverkade @angapov @bingoarun @snowjet @racciari @petr-balogh @odyssey4me @gtema @davidblaisonneau-orange @marsavela @pgaxatte @lingxiankong @openstacker @ckoester2 @AlanCoding @ederst @jovial @jamescassell @bmike78 @GSergeevich @cboylan @dominikholler @acca @dominikholler @nicolasbock @goneri @MaxBab @luis5tb @xinau @krathow @dlbewley @tipabu @ktdreyer @ctrlaltdel @maiqueb @jdwidari-mc @Turmio @jistr @pholica @erolg @kdelee @514amir

**Comment by dagwieers** [comment] 2019-02-21 01:01
If you want to actively lead or are interested to be part of this Working Group, add your name to [the Wiki page](https://github.com/ansible/community/wiki/OpenStack) ! If we have a large enough group, we can start our own OpenStack Working Group.

I started labeling all the OpenStack related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:openstack (40 open PRs)
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:openstack (63 open issues)

PS If you no longer want to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by jamescassell** [comment] 2019-02-21 18:15
I'll step up to lead this one if there's no one more experienced willing to do it.  (I'm fairly new to the OpenStack code, but I manage an OpenStack Private Cloud instance day-to-day.)

What's the process for folks to get added to team_openstack in BOTMETA.yml?

**Comment by dagwieers** [comment] 2019-02-21 18:17
@jamescassell I usually wait a few days to act on who is added to the list. In this case we already have a member-list that is already in $team_openstack. If I don't do it in a single batch, people will get notifications for every new member added. That's not what we want. (I requested an improvement for @ansibot for this issue)

**Comment by pilou-** [comment] 2019-04-18 15:25
Does someone have the time to review this PR ansible/ansible#50285 ?

**Comment by sathiarajah** [comment] 2019-10-06 20:51
I submitted 2 issues on ansible openstack module, os_server & os_stack. We would like to know if the issues are still under investigation/fix has been identified ?

On the os_stack, we are not able to update the existing the existing stack. More information available here - https://github.com/ansible/ansible/issues/59579

Whereas using the os_server, when we add a nic, that nic does not get updated to the existing server. More information available here - https://github.com/ansible/ansible/issues/60045

Appreciate the feedback.

**Comment by satyamsaty** [comment] 2019-10-15 16:18
I am also facing the same issue .Appreciate help .

**Comment by sathiarajah** [comment] 2019-10-24 01:43
We would like to know if the issue ansible/ansible#59579 still under investigation/fix has been identified ?

I have upgraded our openstacksdk to 0.36 and the issue is still observed.

Appreciate the feedback.

**Closed** 2023-11-10 21:13 UTC
Labels: pinboard, openstack
