### ISSUE TITLE
Public Ansible Project Meeting Agenda - March 2021

### ISSUE THREAD

**Issue by bcoca** [ansible/community#591] opened 2021-03-03 23:13 UTC
This repository is for management of all Ansible community related initiatives, such as meetings.

Ansible Support

Bug reports: https://github.com/ansible/ansible/issues/new
IRC: #ansible on irc.freenode.net * Mailing List: https://groups.google.com/forum/#!forum/ansible-project
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.
See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode

**Comment by bcoca** [comment] 2021-03-03 23:16
https://github.com/ansible/ansible/pull/73707

**Comment by felixfontein** [comment] 2021-03-04 06:22
Duplicate of #590.

**Closed** 2021-03-04 06:22 UTC
Labels: core, meeting_agenda
