### ISSUE TITLE
Newbie community pinboard

### ISSUE THREAD

**Issue by Akasurde** [ansible/community#437] opened 2019-02-07 01:38 UTC
[![Github easyfix issues](https://img.shields.io/github/issues/ansible/ansible/easyfix.svg?label=easy+fixes)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:easyfix) [![Newbie pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/437.svg?label=pinboard+update)](https://github.com/ansible/community/issues/437)

Lot of people ask me same question in lot of meetups and conferences - how we can contribute back to Ansible and where can I find `easyfix` issue to get started. 

We would like to help such people by starting this community pinboard where we can post easyfix or low hanging fruits from the Ansible issues list.

Please feel free to ping other people and add issue which you feel can help newbies/newcomers/want-to-be-contributors.

Here is shortcut link for finding [easyfix](https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Aeasyfix)

Thanks.

**Comment by Akasurde** [comment] 2019-02-07 01:42
cc @Devendrabhat @sbulage @digitronik @ptoraskar

**Comment by Akasurde** [comment] 2019-02-07 04:43
cc @raghavtan

**Comment by debhat** [comment] 2019-02-07 07:03
Thanks, @Akasurde. I'll go through that link.

**Comment by raghavtan** [comment] 2019-02-07 08:11
@Akasurde Thanks

**Comment by gundalow** [comment] 2019-02-07 15:21
Would love to know how you get on with this.
You may also be interested in [HOW TO MAKE YOUR MARK: ANSIBLE COMMUNITY CONTRIBUTIONS
](https://www.ansible.com/resources/webinars-training/how-to-make-ansible-community-contributions) slides & video are linked from this page.

Please do shout out if we can help in anyway. I'm happy to guide/mentor anyone.

**Comment by Akasurde** [comment] 2019-02-07 16:19
There is list of open issues segregated by file name - https://ansibullbot.eng.ansible.com/metadata/byfile_sorted.html

**Comment by Akasurde** [comment] 2019-02-08 02:48
cc @kylix3511

**Comment by Akasurde** [comment] 2019-02-08 07:29
cc @amolkahat

**Comment by Akasurde** [comment] 2019-02-12 05:32
cc @akshay196

**Comment by akshay196** [comment] 2019-02-12 05:39
Adding @crackcodecamp in the thread.

**Comment by Akasurde** [comment] 2019-02-12 06:00
cc @sohamdigheoss

**Comment by Akasurde** [comment] 2019-02-12 09:01
cc @anis016

**Comment by Akasurde** [comment] 2019-02-12 09:11
Following line needs to fixed - https://github.com/ansible/ansible/blob/63148b0cc7d396f03215e47ed539145700f32b38/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py#L1644

**Comment by Akasurde** [comment] 2019-02-12 09:20
cc @anurag03

**Comment by Akasurde** [comment] 2019-02-12 10:48
cc @Yadnyawalkya

**Comment by Akasurde** [comment] 2019-02-13 03:45
Fix typo just like - https://github.com/ansible/ansible/blob/46fbcf08bc1998db821714ad65a2b271e4e74f89/lib/ansible/modules/network/fortios/fortios_firewall_auth_portal.py#L48 

Change 'adress' to 'address'. There are ~92 matches in Ansible repo.

**Comment by sbulage** [comment] 2019-02-13 06:25
> Fix typo just like - https://github.com/ansible/ansible/blob/46fbcf08bc1998db821714ad65a2b271e4e74f89/lib/ansible/modules/network/fortios/fortios_firewall_auth_portal.py#L48
> 
> Change 'adress' to 'address'. There are ~92 matches in Ansible repo.

I have fixed it, raising PR

**Comment by anis016** [comment] 2019-02-13 06:26
I was almost done! :(

**Comment by Akasurde** [comment] 2019-02-13 06:28
@sbulage @anis016 We have PR from @amolkahat

**Comment by felixfontein** [comment] 2019-02-13 06:33
Maybe for the next time, when picking a topic from a source like here (where others might be interested too), announce first when you're starting, so that others can see that someone else is already doing it. That's less frustrating for everyone else :)

**Comment by Akasurde** [comment] 2019-02-13 06:35
@felixfontein Good point. There was no issue for this typo so no central place to announce. But going forward we can formalise this. Do you have any easyfix so people here can work on that ? Thanks.

**Comment by amolkahat** [comment] 2019-02-13 06:38
@sbulage already raised one: https://github.com/ansible/ansible/pull/52143

CC: @Akasurde

**Comment by felixfontein** [comment] 2019-02-13 06:46
@Akasurde Yes, got something: in the [FAQ](https://docs.ansible.com/ansible/devel/reference_appendices/faq.html), there are a lot of places where a single backtick is used instead of a double backtick (see [source of FAQ](https://raw.githubusercontent.com/ansible/ansible/devel/docs/docsite/rst/reference_appendices/faq.rst)). These are formatted in *italics* instead as `code`, while most of them propbably should have been the later. This is a common mistake for people more used to Markdown.

I don't know if it also appears in other places in the documentation, or whether all places with a single backtick should be a double backtick, so it is somewhat tedious. There might also other documents ith the same problem.

AFAIR there's no ticket for this.

**Comment by Akasurde** [comment] 2019-02-13 08:20
Before starting work on any issue mentioned here or GH issue page, please add a note saying that you are working on it. So that others will be aware and avoid duplicate efforts.

**Comment by anis016** [comment] 2019-02-13 14:26
hy @Akasurde, can I work on this issue https://github.com/ansible/ansible/issues/51421 ?

**Comment by Akasurde** [comment] 2019-02-15 08:18
@anis016 Sure.

**Comment by Akasurde** [comment] 2019-02-15 08:18
Typo fix - https://github.com/ansible/ansible/blob/6a82827dddbe39d478bd148a66a44185ac52a399/lib/ansible/module_utils/facts/network/base.py#L44

**Comment by anis016** [comment] 2019-02-15 09:00
I am working on this part for fixing the typos

https://github.com/ansible/ansible/blob/6a82827dddbe39d478bd148a66a44185ac52a399/lib/ansible/module_utils/facts/network/base.py#L44

**Comment by anis016** [comment] 2019-02-15 13:12
I plan to work on the typos! I will submit a PR today.

**Comment by Akasurde** [comment] 2019-02-17 12:36
Unsupported argument - 

* https://github.com/ansible/ansible/blob/52d8f9c3973a7ad4c8cbc077ba0733e93b4cae22/lib/ansible/modules/database/postgresql/postgresql_idx.py#L572

**Comment by anis016** [comment] 2019-02-17 19:22
> Typo fixes - While working on issue, please add a note
> 
> * https://github.com/ansible/ansible/blob/6a82827dddbe39d478bd148a66a44185ac52a399/lib/ansible/module_utils/facts/network/base.py#L44
> * Find 'precendence' and change to 'precedence'
> * Find 'arbitary' and change to 'arbitrary'
> * Find 'sucessfully' and change to 'successfully'

merge request submitted: https://github.com/ansible/ansible/pull/52426

**Comment by Akasurde** [comment] 2019-02-18 03:13
Undefined variable - 

* https://github.com/ansible/ansible/blob/4a94bd8d9db2a4fd4a67097370e20dc8e5d90eeb/lib/ansible/modules/cloud/misc/rhevm.py#L593

**Comment by Akasurde** [comment] 2019-02-19 12:13
low hanging fruits - 
https://github.com/ansible/ansible/issues/19463
https://github.com/ansible/ansible/issues/43318

**Comment by Akasurde** [comment] 2019-02-20 04:25
Typo - change from "registed" to "registered"

**Comment by Akasurde** [comment] 2019-02-21 04:45
cc @userimack let me know if you are interested on working any of the above mentioned easyfixes.

**Comment by championshuttler** [comment] 2019-02-21 07:04
> Typo -
> 
>     * change from "registed" to "registered"
> 
>     * change from "formating" to "formatting"
> 
>     * change from "digeset" to "digest"

Hi @Akasurde I would like to give a shot to them, can i take this up?

Thanks

**Comment by userimack** [comment] 2019-02-21 07:22
@championshuttler yes, you can take it up, thanks

**Comment by ptoraskar** [comment] 2019-02-21 07:35
Thank you @Akasurde! Really Appreciate!

**Comment by Akasurde** [comment] 2019-02-26 15:09
Typo - 

1. https://github.com/ansible/ansible/blob/2561fd700096ba83a6880c988fdcb89a91575235/lib/ansible/plugins/__init__.py#L78 - direclty to directly
2. https://github.com/ansible/ansible/blob/2561fd700096ba83a6880c988fdcb89a91575235/lib/ansible/plugins/__init__.py#L83 - standarize to standardize

**Comment by Akasurde** [comment] 2019-03-08 05:23
Typo - 

Change 'dicionaries' to 'dictionaries' overall repo

**Comment by bhavikbhavsar** [comment] 2019-03-11 13:36
Thanks @Akasurde

**Comment by Akasurde** [comment] 2019-11-07 07:09
Typo fix - 'Mutiple' to 'Multiple'

**Comment by sbulage** [comment] 2019-11-07 07:36
@Akasurde PR --> https://github.com/ansible/ansible/pull/64543

**Comment by Akasurde** [comment] 2019-11-08 09:54
PR  https://github.com/ansible/ansible/pull/44375 for https://github.com/ansible/ansible/issues/44340 is about to close, needs love and care.

**Comment by sbulage** [comment] 2019-11-08 10:05
@Akasurde Working on it.

**Comment by sbulage** [comment] 2019-11-08 10:35
@Akasurde PR --> https://github.com/ansible/ansible/pull/64594

**Comment by sbulage** [comment] 2019-11-08 14:23
@valaparthvi

**Comment by Akasurde** [comment] 2019-11-12 08:44
Help required in extending document - https://github.com/ansible/ansible/issues/59125

**Comment by Akasurde** [comment] 2019-11-22 06:14
Help required - https://github.com/ansible/ansible/issues/64628

**Comment by sbulage** [comment] 2019-11-22 06:34
@Akasurde working on it.

**Comment by Akasurde** [comment] 2019-11-24 05:39
https://github.com/ansible/ansible/issues/65223

**Comment by sbulage** [comment] 2019-11-24 07:55
@Akasurde working on it.

**Comment by sbulage** [comment] 2019-11-24 10:58
@Akasurde PR -->  https://github.com/ansible/ansible/pull/65229

**Comment by Akasurde** [comment] 2019-12-04 09:13
Help required - https://github.com/ansible/ansible/issues/40219

**Comment by sbulage** [comment] 2019-12-04 09:42
On it

**Comment by Akasurde** [comment] 2019-12-10 05:48
https://github.com/ansible/ansible/issues/62362

**Comment by Akasurde** [comment] 2019-12-18 02:53
https://github.com/ansible/ansible/issues/65904

**Comment by Akasurde** [comment] 2019-12-24 01:59
https://github.com/ansible/ansible/issues/66038

**Comment by harshblog150** [comment] 2020-06-27 06:33
Thanks @Akasurde

**Comment by Akasurde** [comment] 2020-06-27 06:46
For new people - https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Aeasyfix+label%3Awaiting_on_contributor

**Comment by bmillemathias** [comment] 2020-07-23 15:01
> 
> 
> Help required in extending document - [ansible/ansible#59125](https://github.com/ansible/ansible/issues/59125)

I'm using this bug as an example on `easyfix` labeled bug.

Just adding `easyfix` label will it can help spotting what are for developers fix that can be quick or simple but for someone without any experience it is not easy. Perhaps because she does not know well python or the internals of the projects, or because she does not know how to check her code is correct.

Somethings can be automatically done, the bot can spot bug with easyfix and add link to a page that help starting the project
- how to check out the code
- install the tools
- ...
We can also direct her to a specific room for supporting her.
But more than that I expect mentor and developer tagging `easyfix` to provide some guidance the moment they tagged `easyfix` with few word:
- the general idea to fix the bug or to find information
- the place where to fix in the repo.

Back to the example, for me this is not an easifix, because there is no direction to help the person to fix the problem
> "regex can be configured to perform other tests as well".

I would expect, that the person put a comment with the other tests that could be done and possible a source (like the integration code) where there is examples.

Hopes it helps

**Comment by bmillemathias** [comment] 2020-07-23 16:44
... (continuing)

Perhaps there is a misunderstand on the word `easyfix` because easy is quite a relative word. (we discuss about that on #ansible-devel). The text of the label `easyfix` is "The issue is considered easy to fix by aspiring contributors" seems subject to improvement.

I'd replace `easyfix` label by `new_contributor` and the criteria to be:
- code that can be fixed without a lot of knowledge on the internals (even the word lot is subject to discussion). Module are a good examples. 
- impact of the code is quite low.
- integration test /  unit code are fine I'd say
- is time a criteria ?

**Comment by imjoseangel** [comment] 2020-07-23 21:02
> But more than that I expect mentor and developer tagging `easyfix` to provide some guidance the moment they tagged `easyfix` with few word:

I really like the idea of the `new_contributor` label and most doing mentoring for new contributors. Personally I think some of us wouldn't mind to reserve some time to guide new contributors using IRC and using some examples. I try to do with people near me but I think having a "mentoring" community will open the door of new ideas and opportunities.

Thanks for your comments @bmillemathias

**Comment by imjoseangel** [comment] 2020-07-24 20:36
This is a really good initiative for beginners. It has many forks and contributions. Just added Ansible as a reference https://github.com/firstcontributions/first-contributions


https://firstcontributions.github.io/

**Comment by bmillemathias** [comment] 2020-07-25 08:49
> I'd replace `easyfix` label by `new_contributor` and the criteria to be:

actually there is already a tag `new_contributor` given to people doing their first PR,

**Comment by imjoseangel** [comment] 2020-07-25 09:01
I think is good to have also for issues. The question is also how to proceed and help new contributions from the very beginning.

**Comment by imjoseangel** [comment] 2020-08-01 11:45
Question. Is there any procedure or meeting to request and label an issue to be `easyfix`?

Thank you

**Comment by Akasurde** [comment] 2020-10-27 04:27
Help required - https://github.com/ansible/awx/issues/924

**Comment by Akasurde** [comment] 2020-12-14 15:50
Help required - https://github.com/ansible-collections/community.general/issues/529

**Comment by felixfontein** [comment] 2020-12-23 10:01
Help required - ansible-collections/community.general#1537

**Comment by Akasurde** [comment] 2021-01-01 05:35
Help required - https://github.com/ansible-collections/community.general/issues/674

**Comment by Akasurde** [comment] 2021-01-20 05:59
Help required -

- https://github.com/ansible/ansible/issues/73262

**Comment by felixfontein** [comment] 2021-02-13 11:42
Help wanted (docs update): ansible-collections/community.general#1804

**Closed** 2023-11-10 21:14 UTC
Labels: pinboard, newbie
