### ISSUE TITLE
Logging of (some) IRC channels

### ISSUE THREAD

**Issue by gundalow** [ansible/community#242] opened 2017-09-15 14:56 UTC
During Contributors Summit in San Francisco a number of people asked if we could have `#ansible-network` logged

This is because we've stated that `#ansible-network` will be the official place for discussion, though not everybody has persistent IRC connections

* Do we think it's sensible to have IRC logged
* What are the policy implications for Red Hat
* What Freednode policy
* Where do the logs get stored

**Comment by gregdek** [comment] 2017-09-18 14:24
Historically, zodbot (the Fedora bot) has not done this because the community has been resistant. We can explore some other mechanism for this, or we can use zodbot's meeting functionality very broadly.

**Comment by gregdek** [comment] 2017-10-04 17:45
We discussed in CWG meeting today, and the bigger question is "what issue are we trying to solve?"

If the issue is a fear that crucial conversations are going to happen in #ansible-network and people are going to miss them, that's a fair concern, and the answer isn't necessarily "log every second" -- it's "make sure meeting times are clear and people know when they should be around for key conversations," and "if it looks like an important convo is happening outside of a meeting, start a meeting to capture the output." 

So I think that's the answer. I'll wait for @gundalow feedback here, but right now it looks like we'd close this wontfix.

**Comment by dagwieers** [comment] 2017-10-04 17:50
No, the problem is that various conversations happen outside of meetings and people feel left out of the things that were discussed. Which is the main reason why people are using Slack, as they don't have to be online (or have a dedicated IRC client) in order to be involved in everything that is happening.

What I do is having an IRC client in all the channels I like to be involved in, and have it log everything to disk, which is silly to require from everyone.

So this is a fair request if we are not supporting Slack. I don't like Slack myself, but it is convenient for exactly this. (And inconvenient for a whole lot of other reasons ;-))

**Comment by bcoca** [comment] 2017-10-04 17:55
slack does not have unlimited logs, specially the free version

**Comment by gregdek** [comment] 2017-10-04 17:56
I'm happy to leave this open, then. The only question is, who will implement? It's not hard, it just requires cycles and someplace to maintain the output (which will get lengthy over time).

**Comment by dagwieers** [comment] 2017-10-04 18:01
@bcoca It is not just a matter of unlimited logs, just the fact that you can go back in time without needing to be online for that time is a feature in itself.

I am not in favor of logging, mostly because IRC, like conversations, are fluid in nature and not always something you want to be publicly available (for eternity). And there may also be legal concerns if people are not aware that this is a possibility. But all that still makes IRC less convenient to what people these days are used to.

PS I am looking into installing a bouncer for this particular need. But even in Open Source the IRC ecosystem seems to be shrinking, rather than evolving :-/

**Comment by mscherer** [comment] 2017-10-16 13:44
Doing everything in meeting only work if people read the meeting minutes, and I personally find that searching and reading for conversation on most loggers to be tedious.

If we take for example the log of meetbot as we use them, there is several issue making them not as useful as they could be.

For example:
https://meetbot.fedoraproject.org/ansible-vmware/2017-10-09/ansible_vmware_working_group_meeting.2017-10-09-16.01.log.html 

The timestamp up to the second on the left is too visible, and distracting when reading everything. The fact that everybody appear with the same color make it harder to see who said what too. 

The lack of separation during each meeting topic (like, visually) mean that you have to read the whole log to find it. Even when people use "#topic", this should add a separation directly in the web page (like some blank line), and we should have a index to point to it.

There is also the issue of finding the right logs. The presentation on the log reading website (fedora møte) do show meeting by date, but since we share the room for the whole community, you have to keep in mind the date/time of the meeting to find the logs. Bonus point on having timezone issues (e.g., for people who know when is a meeting, they may have to convert to find the right time).

There is surely way to overcome that, for example, should we post a message each time a bug is mentioned in the channel to the log (meeting or not meeting), so people looking at the bug know this is discussed ?

But meetbot is not maintained (or rather, wasn't last time I looked). Things like botbot.me do fix some issues (search is working, the timestamp is less visible, there is color and nick deduplication) and that could make things better, but it doesn't solve the fundamental issue that we discuss without putting the discussion in a easier to consume format during meetings (and more so outside of it).

**Comment by gregdek** [comment] 2018-05-30 21:40
So this one has been open for a while, and given the comments and lack of hands to implement -- and not even being sure full channel logging is a good idea -- I'm going to close this one. Recommendation is that if it looks like a conversation is taking a turn where it's worth logging, simply turn on meetbot and start an ad hoc meeting.

**Closed by gregdek** 2018-05-30 21:40 UTC
Labels: cwg

**Comment by ssbarnea** [comment] 2020-03-23 13:08
So basically this never happened? I do think that we really need logging on all ansible channels, especially as I was told about some decisions that where made there and there is no proof of these happening or way to backtrace them.

Enabling logging on irc channel is something very easy, in fact we may even be able to re-use logging implemented by others.

**Comment by gregdek** [comment] 2020-03-23 15:09
Again: if decisions are being made, they should be made in the course of a meeting, and that meeting should be recorded by our meeting bot. We use Zodbot, and anyone in channel should be able to use it. Documentation is here: https://fedoraproject.org/wiki/Zodbot

**Comment by gundalow** [comment] 2020-03-29 10:30
Also GitHub is generally the official place of record.7
We do need to get better are recording things in GitHub. I know the gh/ansible/proposals hasn't been used as much. Though for collections we have gotten a lot better at using https://github.com/ansible-collections/overview/issues and overall tracking via https://github.com/orgs/ansible-collections/projects/1
