### ISSUE TITLE
Public Ansible Project Meeting Agenda - June 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#317] opened 2018-05-31 15:32 UTC
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by bcoca** [comment] 2018-06-01 15:15
https://github.com/ansible/ansible/issues/40913

**Comment by bcoca** [comment] 2018-06-04 21:02
https://github.com/ansible/ansible/pull/41078

**Comment by bcoca** [comment] 2018-06-05 20:10
Meeting ended Tue Jun  5 20:06:58 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-05/ansible_irc_core_meeting.2018-06-05-19.04.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-05/ansible_irc_core_meeting.2018-06-05-19.04.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-05/ansible_irc_core_meeting.2018-06-05-19.04.log.html

**Comment by tbouvet** [comment] 2018-06-07 14:01
https://github.com/ansible/ansible/pull/38280

**Comment by farhan7500** [comment] 2018-06-08 10:20
We want to discuss including HPE's hpe3par_cpg. The review comments have been addressed and the CI has also executed successfully. Can we merge the module now?

Looks like ansibot is broken and not updating the labels

https://github.com/ansible/ansible/pull/39656

**Comment by jose-delarosa** [comment] 2018-06-11 04:09
https://github.com/ansible/ansible/pull/41297 
IRC nick is jdelaros1

**Comment by maxamillion** [comment] 2018-06-11 14:11
I'd like to review the inclusion of facts gathering arg to the `k8s` module. Personally I'd like to see a separate module for this since it's already been stated that the lookup module doesn't provide the desired functionality, but I wanted to get the opinion of the group. The PR owner said they would try and attend the meeting, but it's at 5am local time and they might not make it. (understandably so)
https://github.com/ansible/ansible/pull/41088

**Comment by maxamillion** [comment] 2018-06-11 16:15
Would like consensus on how best to handle the scenario in which the user wants to provide more information to the user outside `msgs`. Should this be a warning, new return key int he JSON, $other? https://github.com/ansible/ansible/pull/40723/files

**Comment by mattclay** [comment] 2018-06-11 18:28
Should https://github.com/ansible/ansible/pull/41171 (Introduce inventory.any_unparsed_is_failed configuration setting) be backported to stable-2.6? Although it does add a new configuration entry, it was done to address two bug reports.

**Comment by agaffney** [comment] 2018-06-12 13:02
https://github.com/ansible/ansible/pull/41058

Merging of `default`-derived callback plugin functionality back into `default` to allow mixing/matching of features from those callback plugins.

**Comment by maxamillion** [comment] 2018-06-12 20:47
Meeting ended Tue Jun 12 20:46:35 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-12/ansible_core_community_meeting_2018-06-12.2018-06-12-19.16.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-12/ansible_core_community_meeting_2018-06-12.2018-06-12-19.16.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-12/ansible_core_community_meeting_2018-06-12.2018-06-12-19.16.log.html

**Comment by farhan7500** [comment] 2018-06-13 04:35
We want to discuss including HPE's hpe3par_cpg. The review comments have been addressed and the CI has also executed successfully. Can we merge the module now?

https://github.com/ansible/ansible/pull/39656

**Comment by backbord** [comment] 2018-06-13 06:15
First time contributor here. I'd like to discuss the inclusion of a new strategy "atomic".
The CI executed successfully (a month ago and after today's rebasing) but the PR hasn't received reviews yet.
I would like to see this or a similar strategy added to ansible. If possible, how can I help to move this forward?

https://github.com/ansible/ansible/pull/39602

**Comment by Im0** [comment] 2018-06-13 14:48
Adding success_msg to assert - https://github.com/ansible/ansible/pull/41048

**Comment by sean797** [comment] 2018-06-14 12:55
ability to flush handlers specific handlers https://github.com/ansible/ansible/pull/25573

**Comment by eikef** [comment] 2018-06-14 14:10
I'd like to request a core team review/commit of ansible/ansible#35844 as well as ansible/ansible#35558 (keycloak_realm and keycloak_client new modules; one user had already tested them. They are in the line of other keycloak modules already added.)

There are also some minor bugfix PRs for existing keycloak modules in ansible/ansible#37776 and ansible/ansible#39515 which could use a look-over and commit :-)

**Comment by Akasurde** [comment] 2018-06-14 15:21
* Ansible Installation procedure documentation for Package - https://github.com/ansible/ansible/pull/41437 
* Community review for - https://github.com/ansible/ansible/pull/18437

**Comment by bcoca** [comment] 2018-06-14 16:16
Meeting ended Thu Jun 14 16:15:31 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-14/ansible_core_community_meeting.2018-06-14-15.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-14/ansible_core_community_meeting.2018-06-14-15.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-14/ansible_core_community_meeting.2018-06-14-15.02.log.html

**Comment by jose-delarosa** [comment] 2018-06-18 16:12
https://github.com/ansible/ansible/pull/41656
This is a follow-up to https://github.com/ansible/ansible/pull/41297, where the original module was broken into 3. This submission is for the first module, according to the [grouped modules documentation](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_in_groups.html).
IRC nick is jdelaros1

**Comment by s-hertel** [comment] 2018-06-18 23:19
Discuss expectations for conditionals and undefined variables. Should these tasks have the same outcome? If and where should they fail?
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    assigned_undef: "{{ never_defined }}"
  tasks:
    - debug: msg="{{ never_defined }}"  # succeeds on devel
      when: never_defined is defined
    - debug: msg="{{ assigned_undef }}"
      when: assigned_undef is defined
    - debug: msg="{{ assigned_undef }}"
      when: assigned_undef is not undefined
    - debug: msg="{{ assigned_undef }}"  # is this different than the task above?
      when: not assigned_undef is undefined
```

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    dict_one: {foo: bar}
    dict_two: "{{ dict_one['baz'] }}"
  tasks:
    - debug: msg="{{ dict_one['baz'] }}"  # succeeds on devel
      when: dict_one['baz'] is defined
    - debug: msg="{{ dict_two }}"
      when: dict_two is defined
    - debug: msg="{{ dict_two }}"
      when: dict_two is not undefined
    - debug: msg="{{ dict_two }}"  # is this different than the task above?
      when: not dict_two is undefined
```

**Comment by jtyr** [comment] 2018-06-19 13:51
I would like to discus the following PRs during the meeting on 21st June:

- https://github.com/ansible/ansible/pull/41295
- https://github.com/ansible/ansible/pull/41288
- https://github.com/ansible/ansible/pull/39589
- https://github.com/ansible/ansible/pull/32856

**Comment by bcoca** [comment] 2018-06-19 20:06
Meeting ended Tue Jun 19 20:06:14 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-19/ansible_core_community_meeting.2018-06-19-19.09.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-19/ansible_core_community_meeting.2018-06-19-19.09.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-19/ansible_core_community_meeting.2018-06-19-19.09.log.html

**Comment by caphrim007** [comment] 2018-06-20 23:13
* would like to discuss https://github.com/ansible/community/issues/247#issuecomment-398553610 as @Qalthos recommended the request be asked at core meeting. Logs from networking meeting where this was brought up are https://meetbot.fedoraproject.org/ansible-network/2018-06-20/network_working_group.2018-06-20-15.59.log.html

**Comment by bcoca** [comment] 2018-06-21 17:02
Meeting ended Thu Jun 21 17:01:58 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-21/ansible_core_public_irc_meeting.2018-06-21-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-21/ansible_core_public_irc_meeting.2018-06-21-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-21/ansible_core_public_irc_meeting.2018-06-21-15.00.log.html

**Comment by maxamillion** [comment] 2018-06-22 16:59
Currently `command` and `shell` only support one-liners, there's a request to support multi-line commands via this issue ticket. I'm curious if the collective community has any interest in supporting this use case or if this sort of thing should be offloaded to creating scripts that are `copy`'d and then executed? 

https://github.com/ansible/ansible/issues/12034

**Comment by pilou-** [comment] 2018-06-26 09:19
A regression was very recently backported to 2.6, it breaks some inventory plugins. This should be fixed before the 2.6 release, see ansible/ansible#41888 ansible/ansible#41913 for details.

**Comment by farhan7500** [comment] 2018-06-26 11:40
Want to discuss hpe3par_cpg module. Implemented the review requests from last week's meeting. Need to discuss the integration tests.

https://github.com/ansible/ansible/pull/39656

**Comment by abadger** [comment] 2018-06-26 15:18
Proposal for how to handle file encodings https://github.com/ansible/proposals/issues/121

**Closed** 2018-06-26 19:45 UTC
Labels: core, meeting_agenda

**Comment by bcoca** [comment] 2018-06-26 19:47
Meeting ended Tue Jun 26 19:47:14 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-26/ansible_core_public_irc.2018-06-26-19.07.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-06-26/ansible_core_public_irc.2018-06-26-19.07.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-06-26/ansible_core_public_irc.2018-06-26-19.07.log.html
