### ISSUE TITLE
Public Ansible Project Meeting Agenda - December 2017

### ISSUE THREAD

**Issue by thaumos** [ansible/community#286] opened 2017-11-30 14:45 UTC
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get ~~strike-though~~ `~~strike-though~~`

When creating new agenda ensure `core` and `meeting_agenda` labels are set

**Comment by aalexmonteiro** [comment] 2017-12-05 13:20
A few days ago a review of my PR was made and some information was made about arbitrary data. The information was provided and I definitely need to know a decision. Please.

https://github.com/ansible/ansible/pull/32798

**Comment by eikef** [comment] 2017-12-05 16:19
I'd like to request a commit of ansible/ansible#33184 (zabbix_host integration tests, requested changes by sivel have been applied). Thanks :)

**Comment by thaumos** [comment] 2017-12-05 19:43
2017-12-05 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-05/ansible_core.2017-12-05-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-12-05/ansible_core.2017-12-05-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-05/ansible_core.2017-12-05-19.00.log.html

**Comment by gundalow** [comment] 2017-12-08 16:05
**pep8**
Bulk `autopep8` over `lib/ansible/modules/`

AGREED: 11 (core) and 1 (comiter, but not core) people agreed to do this. Only -1 was from bcoca

PR1: https://github.com/ansible/ansible/pull/33682 MERGED
PR2 https://github.com/ansible/ansible/pull/33690 MERGED


**Style Changes**
 *Agreed: Although `required: false` and `default: null` are redundent (as they are the default), removing them isn't required as they are just "redundent" rather than "incorrect". If while working on a modules and making improvements to the DOCUMENTATION, such as improveing the `descriptions` you wish to remove these lines, that is fine, though not required. 
* Agreed: Understand that PRs that improve the module for a users point of view (improved docs, bug fixes, error handling) are much more welcome that style only PRs. Generally speaking we do not welcome style only PRs, there is still overhead in triaging PRs. 
* Agreed: PRs that improve the quality of module documentation, including propper use of C(..), I(...), M(...), U(...) are welcome. Changes that improve docs/docsite/ are always welcome - In this context doc/ui/presentation/formatting IS important

ACTION: Gundalow to document the above in `dev_guide`

See: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-07/ansible_core.2017-12-07-15.00.log.html for the full discussion

**Comment by gundalow** [comment] 2017-12-08 16:06
2017-12-07 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-07/ansible_core.2017-12-07-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-12-07/ansible_core.2017-12-07-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-07/ansible_core.2017-12-07-15.00.log.html

**Comment by mamunozgonzalez** [comment] 2017-12-11 16:51
We would like to discuss about interface proposed on https://github.com/ansible/ansible/pull/33591.
Proposal can be discussed on Core Team Meeting 2017-12-12, as suggested by @gundalow 
From Fortinet both mangel2 (@mamunozgonzalez) and @thomnico will join.

**Comment by victorssilva** [comment] 2017-12-11 17:06
Would like to discuss https://github.com/ansible/ansible/pull/32104 on the core team meeting of 2017/12/12 as suggested by @tima on https://github.com/ansible/ansible/issues/11418.

**Comment by aalexmonteiro** [comment] 2017-12-11 20:23
A few days ago a review of my PR was made and some information was made about arbitrary data. The information was provided and I definitely need to know a decision. Please.

https://github.com/ansible/ansible/pull/32798

**Comment by abadger** [comment] 2017-12-12 02:02
Buried in this PR: https://github.com/ansible/ansible/pull/33575

was a new feature for arg_spec, key=True.  I think this "key_spec" is too magical for arg_spec.  Here's an example of using it:
```
# Define a foobar parameter in arg_spec like this:
foobar=dict(foo=dict(type='list', key=True), bar=dict())

# Then if the user passes this in their playbook:
- module:
    foobar:
        - 'test-1'
        - 'test-2'

# The module receives this in parameters:
module.params = {'foobar': [ {'foo': 'test-1'}, {'foo': 'test-2'} ] }
```

This transformation is pushing too much logic into the core arg_spec code.  It's no longer just type validation and conversion from other known types, it's actually, unconditionally saying to give it one data structure and it will return a different one.

This should instead be coded so that either the module does the transformation (we can have a helper function if needed) or make it a new callable type (instead of using type='list', use type=my_special_object_creator) and then the my_special_object_creator function can do the transformation.

**Comment by sivel** [comment] 2017-12-12 15:38
https://github.com/ansible/ansible/issues/33306

Gist:

When explicitly providing `when: []` the conditional is evaluated as True. This does not impact any use of variables, only when explicitly typed as `when: []`. This is because the default for a `when` condition is `[]` and we loop all conditions.  `when: foo` actually becomes `when: ['foo']`.

This is very edge case, and I can so no reason for a person to do this, but should we try to change things?  I think no matter what we pick, if the user can represent that in YAML we run into this same issue.  e.g. `when: ~` would match `None` and would return `True` even though `None` is falsy.  Unless we give it some default of like a custom object.

**Comment by sivel** [comment] 2017-12-12 19:59
Rename the recent `cast_list_to_dict` and `cast_dict_to_list` filters added in https://github.com/ansible/ansible/pull/28446

**Comment by thaumos** [comment] 2017-12-12 20:02
2017-12-12 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-12/ansible_core.2017-12-12-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-12-12/ansible_core.2017-12-12-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-12/ansible_core.2017-12-12-19.00.log.html

**Comment by eikef** [comment] 2017-12-13 16:24
I'd like to request a review/merge of ansible/ansible#33419, a new module called keycloak_clienttemplate (which is on the heels of ansible/ansible#31716 which was merged a while ago). The one after this (keycloak_scopes) is already finished, but depends on clienttemplates being in before I can push a useful PR. Thanks :)

**Comment by bcoca** [comment] 2017-12-13 19:40
https://github.com/ansible/ansible/pull/32806

**Comment by thaumos** [comment] 2017-12-14 16:08
2017-12-14 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-14/ansible_core.2017-12-14-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-12-14/ansible_core.2017-12-14-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-14/ansible_core.2017-12-14-15.00.log.html

**Comment by maxamillion** [comment] 2017-12-18 20:48
I would like to discuss the topic of the including or excluding functionality provided by a package manager's plugin to the package manager's Ansible module.

For reference, ~~https://github.com/ansible/ansible/pull/31438~~ is attempting to add `versionlock` functionality to the `yum` Ansible module, however `versionlock` is not a part of core `yum` package manager and is instead a plugin. The plugin is however maintained upstream as part of the official [yum-utils](http://yum.baseurl.org/download/yum-utils/) repository and is part of core RHEL 7 and CentOS 7 (instead of being an add-on third-party repo like [EPEL](https://fedoraproject.org/wiki/EPEL)), but it is not installed by default.

I'm curious what other's thoughts are on this.

Also as a point of note for anyone reviewing the PR as a side effect of this meeting topic, the attempted functionality to be added is not idempotent, but there's not an ideal way to make it idempotent because even the backend yum python API calls don't return anything meaningful to determine change unless we parse an output string.

This brings up another question, is parsing output to determine if a module's execution is idempotent considered acceptable if a more elegant solution does not exist?

**Comment by maxamillion** [comment] 2017-12-18 20:50
https://github.com/ansible/ansible/pull/31450 is proposing adding functionality that s not idempotent, however there's not an ideal way to make it idempotent because even the backend yum python API calls don't return anything meaningful to determine change unless we parse an output string.

Is parsing output to determine if a module's execution is idempotent considered acceptable if a more elegant solution does not exist?

**Comment by gundalow** [comment] 2017-12-19 11:36
Better messages on smart quotes https://github.com/ansible/ansible/issues/33044

**Comment by eikef** [comment] 2017-12-19 12:36
I'd like to ask for guidance on ansible/ansible/pull#33419 and whether the changes implemented are sufficient; the issue is that there are some fields in the API (a config array for protocol mappers in particular) for which an enumeration of all possible options is very, very hard for the existing functionality in Keycloak (since there is no documentation at the API layer, and parsing the source is not as easy as it would first appear) and impossible once you consider that functionality is extensible in Keycloak (i.e. restricting the configurability of custom protocol mappers plugged into Keycloak).
The initial review was done by sivel.

**Comment by thaumos** [comment] 2017-12-19 20:01
2017-12-19 Meeting

Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-19/ansible_core.2017-12-19-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2017-12-19/ansible_core.2017-12-19-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2017-12-19/ansible_core.2017-12-19-19.00.log.html

**Comment by thaumos** [comment] 2017-12-19 20:02
# The meetings on 21-Dec, 26-Dec, and 28-Dec are cancelled.

**Closed** 2017-12-19 20:03 UTC
Labels: core, meeting_agenda
