### ISSUE TITLE
Public Ansible Project Meeting Agenda - Sept 2020

### ISSUE THREAD

**Issue by bcoca** [ansible/community#563] opened 2020-09-01 19:20 UTC
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped. If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been discussed it should get checked off.

If you just want reviewers for your contribution try the #ansible-devel irc channel on freenode.

**Comment by felixfontein** [comment] 2020-09-01 19:46
Duplicate of #560.

**Closed by felixfontein** 2020-09-01 19:46 UTC
Labels: core, meeting_agenda
